template: Hello, %s!
defaultName: Stranger
applicationName: Web Calculator
server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
